### PR TITLE
Make the Language trait mutable

### PR DESCRIPTION
**Pull request by adriangb**

### CODE REVIEW

**Comment by adriangb** [comment]
Side note: you might want to change the Actions security settings:

212133196-5ae743e2-e888-44ae-bdbd-7dfba49fcb9d

**Comment by InquisitivePenguin** [comment]
@adriangb Is this a prerequisite for another change you plan on making, or is this meant to be a general improvement that will enable more flexibility for future implementations?

**Comment by adriangb** [comment]
A bit of both. I first encountered the need for this in #25, but I think it might be useful for other implementations as well. Python needs it to keep track of imports, I implemented that in #25 with a RefCell but it would be a lot nicer if Language was mutable. I thought it would be a simple change but unfortunately, it broke things in other implementations because of borrowing closures, so it may not be that simple.

**Comment by InquisitivePenguin** [comment]
I see! I can help fix the errors here if you want.

**Comment by InquisitivePenguin** [comment]
I've fixed your errors in this PR here: https://github.com/adriangb/typeshare/pull/1

**Comment by adriangb** [comment]
Awesome! Thanks for doing all of the hard work 😄

**Review by InquisitivePenguin — APPROVED** [review]

**Pull request merged**
